# Generated by Django 2.2 on 2019-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mensalista'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMensalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pgto', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mensalista', models.ForeignKey(on_delete=False, to='core.Mensalista')),
            ],
        ),
    ]
